### ISSUE TITLE
Vagrantの導入

### ISSUE THREAD

**Issue by gtaiyou24** [gtaiyou24/tinder_engine#12]
### what
Vagrantを導入する手順は以下の通り。

 - [ ] Vagrantfileの作成
 - [ ] プロビジョンの設定
 - [ ] 他の人で試す

### why
環境設定、バージョンの違いなどによるトラブルから解放されるため

**Comment by gtaiyou24** [comment]
@SuguruOoki 
こんな感じでよろしいんですかね？？？

**Comment by zukako0930** [comment]
vagrantでやるのも良いかもだけど，
- `anaconda`で仮想環境作ると`.yaml`形式で環境情報を出力してくれる．
- その`.yml`ファイルを共有して読み込めば同じ仮想環境を作ることができる．
こっちの方が手軽でいいかも．

`conda`で作った環境をactivate ⇨
`$ conda env export > tinder.yaml` ⇨
カレントディレクトリに`tinder.yaml`ファイルが生成される⇨
`$ conda env create --file myenv.yaml`で仮想環境がそのまま作られる．

手軽にできそうで便利．

**Comment by gtaiyou24** [comment]
#18に議論のissueを設けたので本issueをクローズする
